name: 02 Delivery Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  docker-build-and-push:
    name: Docker Image Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: 1. 소스코드 체크아웃
        uses: actions/checkout@v7

      - name: 2. Docker Buildx 설정 (멀티 플랫폼 빌드 지원 도구)
        uses: docker/setup-buildx-action@v4

      - name: 3. Docker Hub 로그인 인증
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 4. Docker 이미지 빌드 및 Docker Hub 자동 푸시
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mybatis-sns:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mybatis-sns:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max